server:
  env: "production"

eureka:
  client.serviceUrl.defaultZone: http://eureka-prd:1111/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3

spring:
  datasource:
    url: jdbc:mysql://mysqlhsot:3306/${DB_NAME}
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
      naming.strategy: org.hibernate.cfg.DefaultNamingStrategy
    database: mysql
    show-sql: true
    generate-ddl: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
