server:
  env: "develop"

eureka:
  # eureka-dev 代表 eureka 服务的host,如果本地可以在/etc/hosts 文件中配置具体的ip,
  client.serviceUrl.defaultZone: http://eureka-develop:1111/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3

spring:
  datasource:
    url: jdbc:mysql://mysqlhsot:3306/${DB_NAME}
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
      naming.strategy: org.hibernate.cfg.DefaultNamingStrategy
    database: mysql
    show-sql: true
    generate-ddl: false
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

